### Agregar nuevo usuario:
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Luisa Fernandez",
  "age": 35,
  "email": "luisa.fernandez@example.com",
  "city": "Lima",
  "password": "micontraseña",
  "role": "Admin"
}

### Modificar un recurso
PATCH http://localhost:3000/users/e36c5250-24e1-11df-8778-0019b9312238
Content-Type: application/json

{
  "email": "a@gmail.com"
}

### Borrar un usuario
DELETE http://localhost:3000/users/e36c5250-24e1-11df-8778-0019b9312238

